spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: springstudent
    url: jdbc:mysql://localhost:3306/rest_flota_annamar?useSSL=false&allowPublicKeyRetrieval=true
    username: springstudent

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false

    show-sql: false